# Generated by Django 5.0.4 on 2024-06-20 10:15

import django.db.models.deletion
import startapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=startapp.models.catalog_image_path)),
                ('softdelete', models.BooleanField(default=False, verbose_name='Пометить на удаление')),
            ],
            options={
                'verbose_name': 'каталог',
                'verbose_name_plural': 'каталог',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='В наличии')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=startapp.models.product_image_path)),
                ('softdelete', models.BooleanField(default=False, verbose_name='Пометить на удаление')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startapp.catalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товар',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('quantity', models.IntegerField(blank=True, default=1, verbose_name='Количество')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Конечная стоимость')),
                ('session_key', models.CharField(blank=True, max_length=32, verbose_name='Незарегистрированный пользователь')),
                ('softdelete', models.BooleanField(default=False, verbose_name='Пометить на удаление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзина',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=startapp.models.product_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='startapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('review', models.TextField(blank=True, verbose_name='Отзыв')),
                ('star', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Оценка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='startapp.product')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'отзывы',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
