# Generated by Django 5.0.4 on 2024-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Товар оформлен'),
        ),
    ]
